### ISSUE TITLE
installation in the wrong place

### ISSUE THREAD

**Issue by JuliaLawall** [OCamlPro-Iguernlala/ocplib-simplex#6]
By using autoconf, ./configure, make, sudo make install, I end up with ocplib-simplex in /usr/local/lib not /usr/local/lib/ocaml/4.02.3.  It is then not findable with ocamlfind.  The problem seems to be that OCAMLFIND_DESTDIR is not set properly.  make -n install shows OCAMLFIND_DESTDIR=/usr/local/lib/.  I got around the problem by putting the output of make -n install in a file, removing the OCAMLFIND_DESTDIR line and the running the result.  I  am using Ubuntu 16.04.

**Comment by cocreature** [comment]
I’ve run into the same problem. I’ve worked around it by just removing https://github.com/OCamlPro-Iguernlala/ocplib-simplex/blob/master/Makefile.in#L115 but looking at #3, it seems like that line was added for a reason. I’m not sure what the proper solution is but it would be nice if it was at least possible to fix this without patching the makefile. Currently this is not possible since while it’s possible to set `DESTDIR`, `LIBDIR` always appends `/lib` while the final directory is `site-lib` in a standard setup.

**Comment by Earnestly** [comment]
Yes, the breaking commit was 9b6cc06c6aac72c54ef704d540b0597d03ef3dd1

Their mistake was assigning the `@prefix@` to the `DESTDIR` which should **not** be set.

Likewise `LIBDIR` should not be hardcoded as `LIBDIR=$(DESTDIR)/lib`

`DESTDIR` exists to [enable staged installations](https://www.gnu.org/software/automake/manual/html_node/Staged-Installs.html) , this commit makes doing this impossible.

The correct solution would be to provide the installation path as:

```make
LIBDIR=$(shell ocaml -c where)

# ...

# ocamlfind seems unable to create the necessary directory, so create it prior
# to installation instead.
install: all META
	install -dm0755 $(DESTDIR)$(LIBDIR)/ocplib-simplex
	OCAMLFIND_DESTDIR=$(DESTDIR)$(LIBDIR) \
	  ocamlfind install ocplib-simplex src/$(LIBNAME).* src/*.mli META
```

**Comment by Earnestly** [comment]
Here is a small patch I am using to correct this issue:

```diff
diff --git a/Makefile.in b/Makefile.in
index 3c5cf07..3642dc2 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -13,11 +13,10 @@
 # (enclosed in the file LGPL).
 
 # where to install the binaries
-DESTDIR=@prefix@
 # prefix=@prefix@
 # exec_prefix=@exec_prefix@
 # BINDIR=$(DESTDIR)@bindir@
-LIBDIR=$(DESTDIR)/lib/
+LIBDIR ?= $(shell @OCAMLC@ -where)
 # DATADIR=$(DESTDIR)@datadir@/ocplib-simplex
 
 # where to install the man page
@@ -112,7 +111,8 @@ META: config.status
 ##############
 
 install: all META
-	OCAMLFIND_DESTDIR=$(LIBDIR) \
+	install -dm0755 $(DESTDIR)$(LIBDIR)/ocplib-simplex
+	OCAMLFIND_DESTDIR=$(DESTDIR)$(LIBDIR) \
 	  ocamlfind install ocplib-simplex src/$(LIBNAME).* src/*.mli META
```

This allows me to use `make DESTDIR=foo install` correctly but also allows the user to override `LIBDIR` if they want this installed elsehwere.

**Comment by iguerNL** [comment]
Thanks for reporting and commenting the issue.

@Earnestly I pushed a slightly different patch that should use properly both `DESTDIR` and `prefix` variables. In particular, `DESTDIR` is now only used when installing/uninstalling:
https://github.com/OCamlPro-Iguernlala/ocplib-simplex/commit/ d52771f6073938320737e05067f9dec8275db67c

I tested building and installing with OPAM (with a global switch and with a system switch), and with `./configure`, `./configure --prefix ...`, `make install DESTDIR ...`, `make uninstall`. It seems that everything works fine.

@cocreature I replaced `/lib` with `@libdir@`. This makes things more generic.

@JuliaLawall With all these modifications, I was able to achieve what you wanted with
```
./configure --libdir=`ocamlc -where` --prefix=""
```

@treinen This should not break your patch for the isssue https://github.com/OCamlPro-Iguernlala/ocplib-simplex/issues/3. Does it ?

**Comment by Earnestly** [comment]
But now you've created a tight coupling between `prefix` and `libdir` that ends up being  inconsistent with typical usage of `./configure`.  Setting `--prefix` to an empty value and using `--libdir` exclusively is quite awkward and will break any future changes made which doesn't depend on `LIBDIR` as the only entry point for the installation or potential code generation.

Alternatively we could use `--prefix` and `--libdir` but that would now require explicit knowledge of how the `Makefile` is structured such that we must make sure to not include the `prefix` value in the `--libdir` flag.  This again will break when you need to depend on `libdir` and not `LIBDIR`.  (It's a bit of a red flag that you have two variables named `libdir` which represent different things.)

I agree that using `ocamlc -where` in the `Makefile` might have been too hardcoded since it would (practically need to) ignore the `prefix`.  Tough choices.

Nevertheless, it does work a lot better than previously and for my needs this issue can be closed.

Thanks
